services:
  - type: web
    name: cake-diffusion
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free
    numWorkers: 1
